import { Hono } from "hono";
const app = new Hono();
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=utf-8"}})}
function decodeEntities(s=""){return s.replace(/&amp;/g,"&").replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&nbsp;/g," ").replace(/&uuml;/g,"ü").replace(/&ouml;/g,"ö").replace(/&auml;/g,"ä").replace(/&Uuml;/g,"Ü").replace(/&Ouml;/g,"Ö").replace(/&Auml;/g,"Ä").replace(/&szlig;/g,"ß")}
function cleanText(s=""){return decodeEntities(String(s).replace(/\s+/g," ").trim())}
function absUrl(u,base){try{return new URL(u,base).href}catch{return""}}
function stripHtml(html=""){return cleanText(html.replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," "))}
function firstMatch(text,re){const m=text.match(re);return m?.[1]?cleanText(m[1]):""}
function parseListing(html,sourceUrl){
  const text=stripHtml(html),images=[];
  const pushImg=u=>{u=absUrl(u,sourceUrl);if(u&&!images.includes(u)&&/prod\.pictures\.autoscout24\.net/i.test(u))images.push(u)};
  for(const m of html.matchAll(/<meta[^>]+property=["']og:image["'][^>]+content=["']([^"']+)/gi))pushImg(m[1]);
  for(const m of html.matchAll(/(?:src|data-src|data-image-url)\s*=\s*["']([^"']+\.(?:jpg|jpeg|png|webp)[^"']*)["']/gi))pushImg(m[1]);
  for(const m of html.matchAll(/https?:\\?\/\\?\/prod\.pictures\.autoscout24\.net[^"'\\s<>]+/gi))pushImg(m[0].replace(/\\\//g,"/"));
  const styea=firstMatch(html,/"styea"\s*:\s*"?(\d{4})/i),stmon=firstMatch(html,/"stmon"\s*:\s*"?(\d{1,2})/i),stmil=firstMatch(html,/"stmil"\s*:\s*"?(\d+)/i),stkw=firstMatch(html,/"stkw"\s*:\s*"?(\d+)/i),sthp=firstMatch(html,/"sthp"\s*:\s*"?(\d+)/i),cost=firstMatch(html,/"cost"\s*:\s*"?(\d+(?:\.\d+)?)/i);
  const year=styea?(stmon?stmon.padStart(2,"0")+"/"+styea:styea):firstMatch(text,/Erstzulassung\s+(\d{2}\/\d{4})/i);
  const km=stmil||firstMatch(text,/Kilometerstand\s+([\d.]+\s*km)/i).replace(/\s*km/i,"").replace(/\./g,"");
  const range=firstMatch(text,/Elektrische Reichweite(?:\^\d+)?\s+([\d.]+\s*km)/i).replace(/\s*km/i,"").replace(/\./g,"");
  const power=stkw?(sthp?stkw+" kW / "+sthp+" k":""):firstMatch(text,/Leistung\s+(\d+\s*kW(?:\s*\(\d+\s*PS\))?)/i);
  const drive=firstMatch(text,/Antriebsart\s+(Heck|Front|Allrad|Vorderrad|Hinterrad)/i);
  const color=firstMatch(text,/Außenfarbe\s+([A-Za-zÄÖÜäöüß-]+(?:\s+[A-Za-zÄÖÜäöüß-]+){0,2})\s+Farbe laut Hersteller/i)||firstMatch(text,/Außenfarbe\s+([A-Za-zÄÖÜäöüß-]+)/i);
  const slug=new URL(sourceUrl).pathname.split("/angebote/")[1]?.split("-cat_")[0]||"";
  let title=slug?slug.replace(/-elektro-.*$/i,"").replace(/-/g," "):"";
  if(title)title=title.replace(/\b\w/g,m=>m.toUpperCase()).replace(/Q4 E Tron/i,"Q4 e-tron").replace(/Audi Q4 E-tron/i,"Audi Q4 e-tron");
  if(!title)title=firstMatch(html,/<h1[^>]*>([\s\S]*?)<\/h1>/i)||"Nové vozidlo";
  const equipment=[],start=html.search(/Ausstattung/i),end=html.search(/Farbe und Innenausstattung/i);
  if(start>=0){const section=html.slice(start,end>start?end:Math.min(html.length,start+90000));for(const m of section.matchAll(/<li[^>]*>([\s\S]*?)<\/li>/gi)){const item=cleanText(m[1].replace(/<[^>]+>/g," "));if(item&&item.length<120&&!equipment.includes(item)&&!/^(Kaufen|Verkaufen|Informieren|Mehr anzeigen)$/i.test(item))equipment.push(item)}}
  const known=["3-Zonen-Klimaautomatik","Einparkhilfe","Navigationssystem","Panoramadach","Sitzheizung","Standheizung","Tempomat","Android Auto","Apple CarPlay","Bluetooth","DAB-Radio","Soundsystem","LED-Scheinwerfer","Spurhalteassistent","Verkehrszeichenerkennung","Alufelgen","Touchscreen","Komfortschlüssel","Panorama Glas Dach","Audi virtual cockpit","MMI Navigation plus","Audi sound system","Audi drive select","On-board-Ladegerät bis 11 kW (AC)","Hochvolt-Batterie 82 kWh (brutto)","Heckantrieb"];
  for(const item of known)if(text.toLowerCase().includes(item.toLowerCase())&&!equipment.some(x=>x.toLowerCase()===item.toLowerCase()))equipment.push(item);
  return {title:cleanText(title),description:firstMatch(html,/<meta[^>]+property=["']og:description["'][^>]+content=["']([^"']+)/i),year,km,power,range_km:range,drive,color,price_eur:cost?Number(cost):null,images:images.slice(0,40),equipment:equipment.slice(0,100),warnings:[images.length?null:"Nepodarilo sa nájsť fotografie automaticky.",title?null:"Nepodarilo sa nájsť názov vozidla.",year&&km&&power?null:"Niektoré technické údaje sa nepodarilo načítať."].filter(Boolean)};
}
app.get("/api/health",c=>json({ok:true,service:"ReVolt Drive",db:!!c.env.DB,r2:!!c.env.PHOTOS}));
app.post("/api/import",async c=>{const body=await c.req.json().catch(()=>({})),sourceUrl=body.url;if(!sourceUrl)return json({error:"Chýba URL inzerátu."},400);let u;try{u=new URL(sourceUrl)}catch{return json({error:"Neplatná URL."},400)}const allowed=["autoscout24.de","autoscout24.com","mobile.de","suchen.mobile.de"];if(!allowed.some(d=>u.hostname===d||u.hostname.endsWith("."+d)))return json({error:"Tento zdroj zatiaľ nie je v automatickom importéri povolený."},400);try{const r=await fetch(u.href,{headers:{"user-agent":"Mozilla/5.0 (compatible; ReVoltDriveImporter/1.0)","accept-language":"de-DE,de;q=0.9,en;q=0.8"}});if(!r.ok)return json({error:"Zdroj odpovedal HTTP "+r.status+"."},502);return json({ok:true,source:u.href,imported:parseListing(await r.text(),u.href)})}catch{return json({error:"Import sa nepodaril. Skontroluj URL alebo dostupnosť zdroja."},502)}});
app.get("/api/cars",async c=>{if(!c.env.DB)return c.json({error:"D1 databáza DB nie je pripojená k Workeru."},503);try{const {results=[]}=await c.env.DB.prepare("SELECT cars.id,cars.title,cars.subtitle,cars.year,cars.km,cars.power,cars.range_km,cars.drive,cars.color,cars.price_eur,cars.status,cars.description,(SELECT url FROM photos p WHERE p.car_id=cars.id ORDER BY p.position LIMIT 1) AS cover_url FROM cars ORDER BY created_at DESC").all();return c.json({cars:results})}catch(e){return c.json({error:"Chyba D1: "+String(e?.message||e)},500)}});
app.get("/api/cars/:id",async c=>{if(!c.env.DB)return c.json({error:"DB not configured"},503);const id=c.req.param("id");const car=await c.env.DB.prepare("SELECT id,title,subtitle,year,km,power,range_km,drive,color,price_eur,status,description FROM cars WHERE id=?").bind(id).first();if(!car)return c.json({error:"Vozidlo nenájdené"},404);const {results:equipment=[]}=await c.env.DB.prepare("SELECT item FROM equipment WHERE car_id=? ORDER BY rowid").bind(id).all(),{results:photos=[]}=await c.env.DB.prepare("SELECT id,url,position FROM photos WHERE car_id=? ORDER BY position").bind(id).all();return c.json({car,equipment:equipment.map(x=>x.item),photos})});
app.get("/media/:carId/:file",async c=>{if(!c.env.PHOTOS)return c.notFound();const obj=await c.env.PHOTOS.get(c.req.param("carId")+"/"+c.req.param("file"));if(!obj)return c.notFound();const h=new Headers();obj.writeHttpMetadata(h);h.set("cache-control","public,max-age=31536000,immutable");return new Response(obj.body,{headers:h})});
async function storePhotosInR2(c,id,images){if(!c.env.PHOTOS||!c.env.DB)return;for(let i=0;i<(images||[]).length;i++){const src=images[i];try{const ir=await fetch(src,{headers:{"user-agent":"Mozilla/5.0","accept":"image/*,*/*;q=0.8"}});if(!ir.ok)continue;const type=ir.headers.get("content-type")||"image/webp",ext=type.includes("jpeg")||type.includes("jpg")?"jpg":type.includes("png")?"png":"webp",key=id+"/"+String(i).padStart(2,"0")+"."+ext;await c.env.PHOTOS.put(key,await ir.arrayBuffer(),{httpMetadata:{contentType:type}});await c.env.DB.prepare("UPDATE photos SET url=?,processed=1 WHERE car_id=? AND position=?").bind("/media/"+id+"/"+String(i).padStart(2,"0")+"."+ext,id,i).run()}catch{}}}
app.post("/api/cars",async c=>{if(!c.env.DB)return c.json({error:"DB nie je nakonfigurovaná."},503);const b=await c.req.json(),id=b.id||crypto.randomUUID();if(!b.title)return c.json({error:"Názov je povinný."},400);try{await c.env.DB.prepare("INSERT OR REPLACE INTO cars (id,title,subtitle,year,km,power,range_km,drive,color,price_eur,purchase_price_eur,status,description,source_url,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP)").bind(id,b.title,b.subtitle||"",b.year||"",b.km||"",b.power||"",b.range_km||"",b.drive||"",b.color||"",Number(b.price_eur)||0,Number(b.purchase_price_eur)||0,b.status||"available",b.description||"",b.source_url||"").run();await c.env.DB.prepare("DELETE FROM equipment WHERE car_id=?").bind(id).run();for(const item of b.equipment||[])if(item)await c.env.DB.prepare("INSERT INTO equipment(car_id,item) VALUES(?,?)").bind(id,item).run();await c.env.DB.prepare("DELETE FROM photos WHERE car_id=?").bind(id).run();for(let i=0;i<(b.images||[]).length;i++){const src=b.images[i];await c.env.DB.prepare("INSERT INTO photos(id,car_id,url,position,processed) VALUES(?,?,?,?,0)").bind(crypto.randomUUID(),id,src,i).run()}if(c.executionCtx?.waitUntil)c.executionCtx.waitUntil(storePhotosInR2(c,id,b.images||[]));return c.json({ok:true,id,photos_queued:(b.images||[]).length})}catch(e){return c.json({error:"Uloženie zlyhalo: "+String(e?.message||e)},500)}});
app.post("/api/cars/:id/photo-upload-batch",async c=>{if(!c.env.DB||!c.env.PHOTOS)return json({error:"Úložisko nie je nakonfigurované."},503);const id=c.req.param("id");try{const form=await c.req.formData();const files=form.getAll("files").filter(x=>x&&typeof x.arrayBuffer==="function");if(!files.length)return json({error:"Neboli vybrané žiadne fotografie."},400);const existing=await c.env.DB.prepare("SELECT COALESCE(MAX(position),-1) AS maxpos FROM photos WHERE car_id=?").bind(id).first();let pos=Number(existing?.maxpos??-1)+1;const urls=[];for(const file of files){const type=String(file.type||"image/jpeg").split(";")[0];if(!type.startsWith("image/"))continue;const ext=type.includes("png")?"png":type.includes("webp")?"webp":type.includes("gif")?"gif":"jpg";const key=id+"/manual-"+String(pos).padStart(3,"0")+"-"+crypto.randomUUID().slice(0,8)+"."+ext;await c.env.PHOTOS.put(key,await file.arrayBuffer(),{httpMetadata:{contentType:type,cacheControl:"public,max-age=31536000,immutable"}});const url="/media/"+key;await c.env.DB.prepare("INSERT INTO photos(id,car_id,url,position,processed) VALUES(?,?,?,?,0)").bind(crypto.randomUUID(),id,url,pos,0).run();urls.push(url);pos++}if(!urls.length)return json({error:"Nepodarilo sa uložiť žiadnu fotografiu."},400);return json({ok:true,count:urls.length,urls})}catch(e){return json({error:"Nahratie fotografií zlyhalo: "+String(e?.message||e)},500)}});
app.patch("/api/cars/:id",async c=>{if(!c.env.DB)return c.json({error:"DB nie je nakonfigurovaná."},503);const id=c.req.param("id"),b=await c.req.json(),allowed=["title","subtitle","year","km","power","range_km","drive","color","price_eur","purchase_price_eur","status","description"],sets=[],vals=[];for(const k of allowed)if(k in b){sets.push(k+"=?");vals.push(k.includes("price")?Number(b[k]):b[k])}if(!sets.length)return c.json({ok:true});sets.push("updated_at=CURRENT_TIMESTAMP");await c.env.DB.prepare("UPDATE cars SET "+sets.join(",")+" WHERE id=?").bind(...vals,id).run();return c.json({ok:true})});
app.delete("/api/cars/:id",async c=>{if(!c.env.DB)return c.json({error:"DB nie je nakonfigurovaná."},503);await c.env.DB.prepare("DELETE FROM cars WHERE id=?").bind(c.req.param("id")).run();return c.json({ok:true})});
app.all("*",async c=>c.env.ASSETS.fetch(c.req.raw));export default app;