import { Hono } from "hono";
const app = new Hono();
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=utf-8"}})}
function decodeEntities(s=""){return s.replace(/&amp;/g,"&").replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&nbsp;/g," ").replace(/&uuml;/g,"ü").replace(/&ouml;/g,"ö").replace(/&auml;/g,"ä").replace(/&Uuml;/g,"Ü").replace(/&Ouml;/g,"Ö").replace(/&Auml;/g,"Ä").replace(/&szlig;/g,"ß")}
function cleanText(s=""){return decodeEntities(String(s).replace(/\s+/g," ").trim())}
function absUrl(u,base){try{return new URL(u,base).href}catch{return""}}
function stripHtml(html=""){return cleanText(html.replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," "))}
function firstMatch(text,re){const m=text.match(re);return m?.[1]?cleanText(m[1]):""}
function parseListing(html,sourceUrl){
  const text=stripHtml(html),images=[];
  const normalizedHtml=html
    .replace(/\\u002F/gi,"/")
    .replace(/\\\//g,"/")
    .replace(/&amp;/gi,"&");
  const pushImg=u=>{
    u=String(u||"").replace(/\\u002F/gi,"/").replace(/\\\//g,"/").replace(/[),;]+$/,"");
    u=absUrl(u,sourceUrl);
    if(!u||!/prod\.pictures\.autoscout24\.net/i.test(u))return;
    // AutoScout24 appends the requested resolution after the real image file,
    // e.g. /photo.jpg/120x90.webp, /photo.jpg/720x540.webp, etc.
    // Canonicalize by cutting the URL immediately after the original image
    // filename. This makes all resolutions of one photo the same URL.
    try{
      const x=new URL(u);
      const m=x.pathname.match(/^(.*?\.(?:jpg|jpeg|png))(?:\/.*)?$/i);
      if(m)x.pathname=m[1];
      x.search="";
      u=x.href;
    }catch{}
    if(!images.includes(u))images.push(u)
  };  for(const m of normalizedHtml.matchAll(/<meta[^>]+property=["']og:image["'][^>]+content=["']([^"']+)/gi))pushImg(m[1]);
  for(const m of normalizedHtml.matchAll(/(?:src|data-src|data-image-url|data-srcset)\s*=\s*["']([^"']+)["']/gi))pushImg(m[1].split(/\s+/)[0]);
  for(const m of normalizedHtml.matchAll(/https?:\/\/prod\.pictures\.autoscout24\.net\/listing-images\/[^"'<>\s]+/gi))pushImg(m[0]);
  const styea=firstMatch(html,/"styea"\s*:\s*"?(\d{4})/i),stmon=firstMatch(html,/"stmon"\s*:\s*"?(\d{1,2})/i),stmil=firstMatch(html,/"stmil"\s*:\s*"?(\d+)/i),stkw=firstMatch(html,/"stkw"\s*:\s*"?(\d+)/i),sthp=firstMatch(html,/"sthp"\s*:\s*"?(\d+)/i),cost=firstMatch(html,/"cost"\s*:\s*"?(\d+(?:\.\d+)?)/i)||firstMatch(html,/"vehiclePrice"\s*:\s*"?(\d+(?:\.\d+)?)/i)||firstMatch(html,/"salePrice"\s*:\s*"?(\d+(?:\.\d+)?)/i);
  function parsePriceNumber(s=""){const v=String(s||"").replace(/\u00a0/g," ").replace(/\s/g,"").replace(/€/g,"");if(/\d{1,3}(?:[. ]\d{3})+(?:,\d+)?$/.test(v))return Number(v.replace(/\./g,"").replace(/,/g,"."));if(/\d+(?:,\d+)?$/.test(v))return Number(v.replace(/,/g,"."));return null}
  const priceSource=cleanText(html.replace(/<[^>]+>/g," "));\n  const priceNet=firstMatch(text,/Netto(?:-Kaufpreis)?[^0-9€]{0,120}([0-9][0-9. ]{2,8}(?:,[0-9]{1,2})?)\s*€/i)||firstMatch(priceSource,/Netto(?:-Kaufpreis)?[^0-9€]{0,120}([0-9][0-9. ]{2,8}(?:,[0-9]{1,2})?)\s*€/i)||firstMatch(text,/Netto[^0-9]{0,120}([0-9][0-9. ]{2,8}(?:,[0-9]{1,2})?)\s*€/i)||firstMatch(priceSource,/Netto[^0-9]{0,120}([0-9][0-9. ]{2,8}(?:,[0-9]{1,2})?)\s*€/i);
  const priceGross=firstMatch(text,/Brutto(?:-Kaufpreis)?[^0-9€]{0,120}([0-9][0-9. ]{2,8}(?:,[0-9]{1,2})?)\s*€/i)||firstMatch(priceSource,/Brutto(?:-Kaufpreis)?[^0-9€]{0,120}([0-9][0-9. ]{2,8}(?:,[0-9]{1,2})?)\s*€/i)||firstMatch(text,/Brutto[^0-9]{0,120}([0-9][0-9. ]{2,8}(?:,[0-9]{1,2})?)\s*€/i)||firstMatch(priceSource,/Brutto[^0-9]{0,120}([0-9][0-9. ]{2,8}(?:,[0-9]{1,2})?)\s*€/i);
  const parsedNet=parsePriceNumber(priceNet),parsedGross=parsePriceNumber(priceGross);
  const year=styea?(stmon?stmon.padStart(2,"0")+"/"+styea:styea):firstMatch(text,/Erstzulassung\s+(\d{2}\/\d{4})/i);
  const km=stmil||firstMatch(text,/Kilometerstand\s+([\d.]+\s*km)/i).replace(/\s*km/i,"").replace(/\./g,"");
  const range=firstMatch(text,/Elektrische Reichweite(?:\^\d+)?\s+([\d.]+\s*km)/i).replace(/\s*km/i,"").replace(/\./g,"");
  const power=stkw?(sthp?stkw+" kW / "+sthp+" k":""):firstMatch(text,/Leistung\s+(\d+\s*kW(?:\s*\(\d+\s*PS\))?)/i);
  const driveSource=cleanText(html.replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," "));
  const driveRe=/Antriebsart[\s\S]{0,300}?(Heckantrieb|Heck|Frontantrieb|Front|Allradantrieb|Allrad|Vorderradantrieb|Vorderrad|Hinterradantrieb|Hinterrad)/i;
  const rawDrive=firstMatch(text,driveRe)||firstMatch(driveSource,driveRe)||firstMatch(html,driveRe);
  const driveMap={"Heck":"Pohon zadných kolies","Heckantrieb":"Pohon zadných kolies","Hinterrad":"Pohon zadných kolies","Hinterradantrieb":"Pohon zadných kolies","Front":"Pohon predných kolies","Frontantrieb":"Pohon predných kolies","Vorderrad":"Pohon predných kolies","Vorderradantrieb":"Pohon predných kolies","Allrad":"Pohon všetkých kolies","Allradantrieb":"Pohon všetkých kolies"};
  const drive=driveMap[rawDrive]||rawDrive;
  const rawColor=firstMatch(text,/Außenfarbe\s+([A-Za-zÄÖÜäöüß-]+(?:\s+[A-Za-zÄÖÜäöüß-]+){0,2})\s+Farbe laut Hersteller/i)||firstMatch(text,/Außenfarbe\s+([A-Za-zÄÖÜäöüß-]+)/i);
  const colorMap={"Weiß":"Biela","Schwarz":"Čierna","Grau":"Sivá","Silber":"Strieborná","Blau":"Modrá","Rot":"Červená","Grün":"Zelená","Braun":"Hnedá","Beige":"Béžová","Gelb":"Žltá","Orange":"Oranžová"};
  const color=rawColor.split(/\s+/).map(x=>colorMap[x]||x).join(" ");
  const slug=new URL(sourceUrl).pathname.split("/angebote/")[1]?.split("-cat_")[0]||"";
  let title=slug?slug.replace(/-elektro-.*$/i,"").replace(/-/g," "):"";
  if(title)title=title.replace(/\b\w/g,m=>m.toUpperCase()).replace(/Q4 E Tron/i,"Q4 e-tron").replace(/Audi Q4 E-tron/i,"Audi Q4 e-tron");
  if(!title)title=firstMatch(html,/<h1[^>]*>([\s\S]*?)<\/h1>/i)||"Nové vozidlo";
  const equipment=[];
  const allLi=[];
  for(const m of html.matchAll(/<li[^>]*>([\s\S]*?)<\/li>/gi)){
    const item=cleanText(m[1].replace(/<[^>]+>/g," "));
    if(item&&item.length<120&&!allLi.includes(item))allLi.push(item)
  }
  const anchors=["3-Zonen-Klimaautomatik","Einparkhilfe","Navigationssystem","Sitzheizung","Tempomat","Bluetooth","ABS","Alufelgen"];
  let eqStart=allLi.findIndex(x=>anchors.some(a=>x.toLowerCase()===a.toLowerCase()));
  if(eqStart>=0){
    for(let i=eqStart;i<allLi.length;i++){
      const item=allLi[i];
      if(/^Mehr anzeigen$/i.test(item))break;
      if(!/^(Komfort|Unterhaltung\/Media|Sicherheit|Extras)$/i.test(item)&&!equipment.includes(item))equipment.push(item)
    }
  }
  const equipMap={
    "3-Zonen-Klimaautomatik":"3-zónová automatická klimatizácia","Armlehne":"Lakťová opierka","Einparkhilfe":"Parkovacie senzory","Einparkhilfe Rückfahrkamera":"Parkovacie senzory s cúvacou kamerou","Einparkhilfe Sensoren hinten":"Zadné parkovacie senzory","Einparkhilfe Sensoren vorne":"Predné parkovacie senzory","Elektrische Fensterheber":"Elektrické ovládanie okien","Elektrische Heckklappe":"Elektrické otváranie kufra","Elektrische Seitenspiegel":"Elektricky nastaviteľné spätné zrkadlá","Getönte Scheiben":"Tónované sklá","Lederausstattung":"Kožené čalúnenie","Lederlenkrad":"Kožený volant","Lichtsensor":"Svetelný senzor","Multifunktionslenkrad":"Multifunkčný volant","Navigationssystem":"Navigačný systém","Regensensor":"Dažďový senzor","Schlüssellose Zentralverriegelung":"Bezkľúčové odomykanie a zamykanie","Sitzheizung":"Vyhrievané sedadlá","teilb. Rücksitzbank":"Delené zadné sedadlá","Tempomat":"Tempomat","Bluetooth":"Bluetooth","Bordcomputer":"Palubný počítač","DAB-Radio":"DAB rádio","Freisprecheinrichtung":"Handsfree","Radio":"Rádio","Soundsystem":"Audiosystém","Volldigitales Kombiinstrument":"Digitálny prístrojový panel","ABS":"ABS","Abstandstempomat":"Adaptívny tempomat","Abstandswarner":"Upozornenie na odstup","Beifahrerairbag":"Airbag spolujazdca","ESP":"ESP","Fahrerairbag":"Airbag vodiča","Geschwindigkeits-begrenzungsanlage":"Obmedzovač rýchlosti","Isofix":"ISOFIX","Kopfairbag":"Hlavové airbagy","LED-Scheinwerfer":"LED svetlomety","LED-Tagfahrlicht":"LED denné svietenie","Notbremsassistent":"Asistent núdzového brzdenia","Notrufsystem":"Núdzové volanie","Reifendruckkontrollsystem":"Kontrola tlaku v pneumatikách","Seitenairbag":"Bočné airbagy","Servolenkung":"Posilňovač riadenia","Spurhalteassistent":"Asistent udržiavania v jazdnom pruhu","Tagfahrlicht":"Denné svietenie","Totwinkel-Assistent":"Asistent mŕtveho uhla","Traktionskontrolle":"Kontrola trakcie","Verkehrszeichenerkennung":"Rozpoznávanie dopravných značiek","Wegfahrsperre":"Imobilizér","Zentralverriegelung":"Centrálne zamykanie","Alufelgen":"Hliníkové disky","Ambientebeleuchtung":"Ambientné osvetlenie","Schaltwippen":"Páčky radenia pod volantom","Sommerreifen":"Letné pneumatiky","Sportfahrwerk":"Športový podvozok","Sportpaket":"Športový paket","Sportsitze":"Športové sedadlá","Sprachsteuerung":"Hlasové ovládanie","Touchscreen":"Dotyková obrazovka"
  };
  for(let i=0;i<equipment.length;i++)equipment[i]=equipMap[equipment[i]]||equipment[i];
  // AutoScout24 dnes časť výbavy posiela aj v skriptoch/JSON namiesto klasických <li>.
  // Preto pre fallback výbavy používame aj text zo skriptov, ale iba pre známe názvy výbavy.
  const equipmentText=cleanText(html.replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," "));
  const knownMap={
    "3-Zonen-Klimaautomatik":"3-zónová automatická klimatizácia","Armlehne":"Lakťová opierka","Einparkhilfe":"Parkovacie senzory","Einparkhilfe Rückfahrkamera":"Parkovacie senzory s cúvacou kamerou","Einparkhilfe Sensoren hinten":"Zadné parkovacie senzory","Einparkhilfe Sensoren vorne":"Predné parkovacie senzory","Elektrische Fensterheber":"Elektrické ovládanie okien","Elektrische Heckklappe":"Elektrické otváranie kufra","Elektrische Seitenspiegel":"Elektricky nastaviteľné spätné zrkadlá","Getönte Scheiben":"Tónované sklá","Lederausstattung":"Kožené čalúnenie","Lederlenkrad":"Kožený volant","Lichtsensor":"Svetelný senzor","Multifunktionslenkrad":"Multifunkčný volant","Navigationssystem":"Navigačný systém","Regensensor":"Dažďový senzor","Schlüssellose Zentralverriegelung":"Bezkľúčové odomykanie a zamykanie","Sitzheizung":"Vyhrievané sedadlá","teilb. Rücksitzbank":"Delené zadné sedadlá","Tempomat":"Tempomat","Bluetooth":"Bluetooth","Bordcomputer":"Palubný počítač","DAB-Radio":"DAB rádio","Freisprecheinrichtung":"Handsfree","Radio":"Rádio","Soundsystem":"Audiosystém","Volldigitales Kombiinstrument":"Digitálny prístrojový panel","ABS":"ABS","Abstandstempomat":"Adaptívny tempomat","Abstandswarner":"Upozornenie na odstup","Beifahrerairbag":"Airbag spolujazdca","ESP":"ESP","Fahrerairbag":"Airbag vodiča","Geschwindigkeits-begrenzungsanlage":"Obmedzovač rýchlosti","Isofix":"ISOFIX","Kopfairbag":"Hlavové airbagy","LED-Scheinwerfer":"LED svetlomety","LED-Tagfahrlicht":"LED denné svietenie","Notbremsassistent":"Asistent núdzového brzdenia","Notrufsystem":"Núdzové volanie","Reifendruckkontrollsystem":"Kontrola tlaku v pneumatikách","Seitenairbag":"Bočné airbagy","Servolenkung":"Posilňovač riadenia","Spurhalteassistent":"Asistent udržiavania v jazdnom pruhu","Tagfahrlicht":"Denné svietenie","Totwinkel-Assistent":"Asistent mŕtveho uhla","Traktionskontrolle":"Kontrola trakcie","Verkehrszeichenerkennung":"Rozpoznávanie dopravných značiek","Wegfahrsperre":"Imobilizér","Zentralverriegelung":"Centrálne zamykanie","Alufelgen":"Hliníkové disky","Ambientebeleuchtung":"Ambientné osvetlenie","Schaltwippen":"Páčky radenia pod volantom","Sommerreifen":"Letné pneumatiky","Sportfahrwerk":"Športový podvozok","Sportpaket":"Športový paket","Sportsitze":"Športové sedadlá","Sprachsteuerung":"Hlasové ovládanie","Touchscreen":"Dotyková obrazovka",
    "virtual cockpit":"Digitálny prístrojový panel (virtual cockpit)","Kombiinstrument digital":"Digitálny prístrojový panel (virtual cockpit)","Sound-System Sonos Premium":"Sonos Premium audiosystém","Audi connect":"Audi connect","MMI Navigation Plus":"MMI Navigation Plus","MMI Navigation Plus mit MMI Touch":"MMI Navigation Plus s MMI Touch","Audi Drive Select":"Audi drive select","Rückfahrkamera":"Cúvacia kamera","Sport-Fahrwerk":"Športový podvozok","Komfort-Klimaautomatik 3-Zonen":"Komfortná 3-zónová automatická klimatizácia","Komfortschlüssel":"Komfortový kľúč","S line":"S line paket","Leder Feinnappa":"Koža Feinnappa","Sportsitze vorn":"Športové predné sedadlá","Sitzheizung vorn":"Vyhrievané predné sedadlá","Multifunktion":"Multifunkčný volant","Kontur / Ambientebeleuchtungs-Paket":"Kontúrové / ambientné osvetlenie","Optik-Paket schwarz":"Čierny optický paket","Sicherheits-Paket plus":"Bezpečnostný paket plus","Assistenz-Paket plus":"Asistenčný paket plus","Antriebsart: Heckantrieb":"Pohon zadných kolies","HV-Batterie 55 kWh":"HV batéria 55 kWh","HV-Batterie 55 kWh brutto / 52 kWh netto":"HV batéria 55 kWh brutto / 52 kWh netto","On-Board-Ladegerät (bis 7,2 kW)":"Palubná AC nabíjačka do 7,2 kW","Panoramadach":"Panoramatická strecha","Standheizung":"Nezávislé kúrenie","Android Auto":"Android Auto","Apple CarPlay":"Apple CarPlay","Akustikglas":"Akustické sklá","Metallic-Lackierung":"Metalický lak","Sitzbezug Leder":"Kožené čalúnenie","Wärmeschutzverglasung":"Tepelnoizolačné sklá"
  };
  for(const [de,sk] of Object.entries(knownMap)){
    if(equipmentText.toLowerCase().includes(de.toLowerCase())&&!equipment.some(x=>x.toLowerCase()===sk.toLowerCase()))equipment.push(sk);
  }
    return {title:cleanText(title),description:firstMatch(html,/<meta[^>]+property=["']og:description["'][^>]+content=["']([^"']+)/i),year,km,power,range_km:range,drive,color,price_eur:parsedNet||parsedGross||(cost?Number(cost):null),images:images.slice(0,40),equipment:equipment.slice(0,100),warnings:[images.length?null:"Nepodarilo sa nájsť fotografie automaticky.",title?null:"Nepodarilo sa nájsť názov vozidla.",year&&km&&power?null:"Niektoré technické údaje sa nepodarilo načítať."].filter(Boolean)};
}
app.get("/api/health",c=>json({ok:true,service:"ReVolt Drive",db:!!c.env.DB,r2:!!c.env.PHOTOS}));
app.post("/api/import",async c=>{const body=await c.req.json().catch(()=>({})),sourceUrl=body.url;if(!sourceUrl)return json({error:"Chýba URL inzerátu."},400);let u;try{u=new URL(sourceUrl)}catch{return json({error:"Neplatná URL."},400)}const allowed=["autoscout24.de","autoscout24.com","mobile.de","suchen.mobile.de"];if(!allowed.some(d=>u.hostname===d||u.hostname.endsWith("."+d)))return json({error:"Tento zdroj zatiaľ nie je v automatickom importéri povolený."},400);try{const r=await fetch(u.href,{headers:{"user-agent":"Mozilla/5.0 (compatible; ReVoltDriveImporter/1.0)","accept-language":"de-DE,de;q=0.9,en;q=0.8"}});if(!r.ok)return json({error:"Zdroj odpovedal HTTP "+r.status+"."},502);return json({ok:true,source:u.href,imported:parseListing(await r.text(),u.href)})}catch{return json({error:"Import sa nepodaril. Skontroluj URL alebo dostupnosť zdroja."},502)}});
app.get("/api/cars",async c=>{if(!c.env.DB)return c.json({error:"D1 databáza DB nie je pripojená k Workeru."},503);try{const {results=[]}=await c.env.DB.prepare("SELECT cars.id,cars.title,cars.subtitle,cars.year,cars.km,cars.power,cars.range_km,cars.drive,cars.color,cars.price_eur,cars.purchase_price_eur,cars.status,cars.description,(SELECT url FROM photos p WHERE p.car_id=cars.id ORDER BY p.position LIMIT 1) AS cover_url FROM cars ORDER BY created_at DESC").all();return c.json({cars:results})}catch(e){return c.json({error:"Chyba D1: "+String(e?.message||e)},500)}});
app.get("/api/cars/:id",async c=>{if(!c.env.DB)return c.json({error:"DB not configured"},503);const id=c.req.param("id");const car=await c.env.DB.prepare("SELECT id,title,subtitle,year,km,power,range_km,drive,color,price_eur,status,description FROM cars WHERE id=?").bind(id).first();if(!car)return c.json({error:"Vozidlo nenájdené"},404);const {results:equipment=[]}=await c.env.DB.prepare("SELECT item FROM equipment WHERE car_id=? ORDER BY rowid").bind(id).all(),{results:photos=[]}=await c.env.DB.prepare("SELECT id,url,position FROM photos WHERE car_id=? ORDER BY position").bind(id).all();return c.json({car,equipment:equipment.map(x=>x.item),photos})});
app.get("/media/:carId/:file",async c=>{if(!c.env.PHOTOS)return c.notFound();const obj=await c.env.PHOTOS.get(c.req.param("carId")+"/"+c.req.param("file"));if(!obj)return c.notFound();const h=new Headers();obj.writeHttpMetadata(h);h.set("cache-control","public,max-age=31536000,immutable");return new Response(obj.body,{headers:h})});
async function storePhotosInR2(c,id,images){if(!c.env.PHOTOS||!c.env.DB)return;for(let i=0;i<(images||[]).length;i++){const src=images[i];try{const ir=await fetch(src,{headers:{"user-agent":"Mozilla/5.0","accept":"image/*,*/*;q=0.8"}});if(!ir.ok)continue;const type=ir.headers.get("content-type")||"image/webp",ext=type.includes("jpeg")||type.includes("jpg")?"jpg":type.includes("png")?"png":"webp",key=id+"/"+String(i).padStart(2,"0")+"."+ext;await c.env.PHOTOS.put(key,await ir.arrayBuffer(),{httpMetadata:{contentType:type}});await c.env.DB.prepare("UPDATE photos SET url=?,processed=1 WHERE car_id=? AND position=?").bind("/media/"+id+"/"+String(i).padStart(2,"0")+"."+ext,id,i).run()}catch{}}}
app.post("/api/cars",async c=>{if(!c.env.DB)return c.json({error:"DB nie je nakonfigurovaná."},503);const b=await c.req.json(),id=b.id||crypto.randomUUID();if(!b.title)return c.json({error:"Názov je povinný."},400);try{await c.env.DB.prepare("INSERT INTO cars (id,title,subtitle,year,km,power,range_km,drive,color,price_eur,purchase_price_eur,status,description,source_url,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET title=excluded.title,subtitle=excluded.subtitle,year=excluded.year,km=excluded.km,power=excluded.power,range_km=excluded.range_km,drive=excluded.drive,color=excluded.color,price_eur=excluded.price_eur,purchase_price_eur=excluded.purchase_price_eur,status=excluded.status,description=excluded.description,source_url=excluded.source_url,updated_at=CURRENT_TIMESTAMP").bind(id,b.title,b.subtitle||"",b.year||"",b.km||"",b.power||"",b.range_km||"",b.drive||"",b.color||"",Number(b.price_eur)||0,Number(b.purchase_price_eur)||0,b.status||"available",b.description||"",b.source_url||"").run();await c.env.DB.prepare("DELETE FROM equipment WHERE car_id=?").bind(id).run();for(const item of b.equipment||[])if(item)await c.env.DB.prepare("INSERT INTO equipment(car_id,item) VALUES(?,?)").bind(id,item).run();let photosQueued=0;if(Array.isArray(b.images)){await c.env.DB.prepare("DELETE FROM photos WHERE car_id=?").bind(id).run();for(let i=0;i<b.images.length;i++){const src=b.images[i];await c.env.DB.prepare("INSERT INTO photos(id,car_id,url,position,processed) VALUES(?,?,?,?,0)").bind(crypto.randomUUID(),id,src,i,0).run()}photosQueued=b.images.length;if(c.executionCtx?.waitUntil)c.executionCtx.waitUntil(storePhotosInR2(c,id,b.images))}return c.json({ok:true,id,photos_queued:photosQueued})}catch(e){return c.json({error:"Uloženie zlyhalo: "+String(e?.message||e)},500)}});
app.post("/api/cars/:id/photos/reorder",async c=>{if(!c.env.DB)return json({error:"DB nie je nakonfigurovaná."},503);const id=c.req.param("id");try{const b=await c.req.json();const urls=Array.isArray(b.urls)?b.urls:[];const rows=await c.env.DB.prepare("SELECT id,url FROM photos WHERE car_id=?").bind(id).all();const byUrl=new Map((rows.results||[]).map(x=>[x.url,x.id]));for(let i=0;i<urls.length;i++){const pid=byUrl.get(urls[i]);if(pid)await c.env.DB.prepare("UPDATE photos SET position=? WHERE id=? AND car_id=?").bind(i,pid,id).run()}return json({ok:true})}catch(e){return json({error:"Poradie fotografií sa nepodarilo uložiť: "+String(e?.message||e)},500)}});app.delete("/api/cars/:id/photo",async c=>{if(!c.env.DB)return json({error:"DB nie je nakonfigurovaná."},503);const id=c.req.param("id");try{const b=await c.req.json();const url=String(b.url||"");const row=await c.env.DB.prepare("SELECT id,url FROM photos WHERE car_id=? AND url=?").bind(id,url).first();if(!row)return json({error:"Fotografia nebola nájdená."},404);if(c.env.PHOTOS&&url.startsWith("/media/"))await c.env.PHOTOS.delete(url.slice(7));await c.env.DB.prepare("DELETE FROM photos WHERE id=? AND car_id=?").bind(row.id,id).run();const rows=await c.env.DB.prepare("SELECT id FROM photos WHERE car_id=? ORDER BY position").bind(id).all();for(let i=0;i<(rows.results||[]).length;i++)await c.env.DB.prepare("UPDATE photos SET position=? WHERE id=?").bind(i,rows.results[i].id).run();return json({ok:true})}catch(e){return json({error:"Fotografiu sa nepodarilo zmazať: "+String(e?.message||e)},500)}});app.post("/api/cars/:id/photo-import",async c=>{if(!c.env.DB||!c.env.PHOTOS)return json({error:"Úložisko nie je nakonfigurované."},503);const id=c.req.param("id");try{const car=await c.env.DB.prepare("SELECT source_url FROM cars WHERE id=?").bind(id).first();if(!car?.source_url)return json({error:"Vozidlo nemá uložený pôvodný link."},400);const u=new URL(car.source_url);const allowed=["autoscout24.de","autoscout24.com","mobile.de","suchen.mobile.de"];if(!allowed.some(d=>u.hostname===d||u.hostname.endsWith("."+d)))return json({error:"Tento zdroj nie je podporovaný."},400);const r=await fetch(u.href,{headers:{"user-agent":"Mozilla/5.0 (compatible; ReVoltDriveImporter/1.0)","accept-language":"de-DE,de;q=0.9,en;q=0.8"}});if(!r.ok)return json({error:"Zdroj odpovedal HTTP "+r.status+"."},502);const parsed=parseListing(await r.text(),u.href);
if(parsed.color||parsed.drive){await c.env.DB.prepare("UPDATE cars SET color=COALESCE(?,color),drive=COALESCE(?,drive),updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(parsed.color||null,parsed.drive||null,id).run();}
if(Array.isArray(parsed.equipment)&&parsed.equipment.length){
  await c.env.DB.prepare("DELETE FROM equipment WHERE car_id=?").bind(id).run();
  for(const item of parsed.equipment)if(item)await c.env.DB.prepare("INSERT INTO equipment(car_id,item) VALUES(?,?)").bind(id,item).run();
}
if(!parsed.images?.length)return json({error:"Na pôvodnom inzeráte sa nepodarilo nájsť fotografie."},404);const old=await c.env.DB.prepare("SELECT id,url FROM photos WHERE car_id=? AND url LIKE ?").bind(id,"/media/"+id+"/auto-%").all();for(const row of old.results||[]){if(c.env.PHOTOS&&row.url.startsWith("/media/"))await c.env.PHOTOS.delete(row.url.slice(7));await c.env.DB.prepare("DELETE FROM photos WHERE id=? AND car_id=?").bind(row.id,id).run()}const max=await c.env.DB.prepare("SELECT COALESCE(MAX(position),-1) AS maxpos FROM photos WHERE car_id=?").bind(id).first();let pos=Number(max?.maxpos??-1)+1,count=0;for(const src of parsed.images.slice(0,40)){try{
      const candidates=[
        src+"/1280x960.webp",
        src+"/2560x1920.webp",
        src
      ];
      let ir=null;
      for(const candidate of candidates){
        const rr=await fetch(candidate,{headers:{
          "user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/131 Safari/537.36",
          "accept":"image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8",
          "referer":car.source_url
        }});
        if(rr.ok){ir=rr;break}
      }
      if(!ir)continue;
      const type=(ir.headers.get("content-type")||"image/jpeg").split(";")[0];
      if(!type.startsWith("image/"))continue;
      const ext=type.includes("png")?"png":type.includes("webp")?"webp":type.includes("gif")?"gif":"jpg";
      const key=id+"/auto-"+String(pos).padStart(3,"0")+"-"+crypto.randomUUID().slice(0,8)+"."+ext;
      await c.env.PHOTOS.put(key,await ir.arrayBuffer(),{httpMetadata:{contentType:type,cacheControl:"public,max-age=31536000,immutable"}});
      const url="/media/"+key;
      await c.env.DB.prepare("INSERT INTO photos(id,car_id,url,position,processed) VALUES(?,?,?,?,1)").bind(crypto.randomUUID(),id,url,pos).run();
      pos++;count++
    }catch{}}if(!count)return json({error:"Fotografie sa z inzerátu nepodarilo stiahnuť."},502);return json({ok:true,count})}catch(e){return json({error:"Automatický import fotografií zlyhal: "+String(e?.message||e)},500)}});app.post("/api/cars/:id/photo-upload-batch",async c=>{if(!c.env.DB||!c.env.PHOTOS)return json({error:"Úložisko nie je nakonfigurované."},503);const id=c.req.param("id");try{const form=await c.req.formData();const files=form.getAll("files").filter(x=>x&&typeof x.arrayBuffer==="function");if(!files.length)return json({error:"Neboli vybrané žiadne fotografie."},400);const existing=await c.env.DB.prepare("SELECT COALESCE(MAX(position),-1) AS maxpos FROM photos WHERE car_id=?").bind(id).first();let pos=Number(existing?.maxpos??-1)+1;const urls=[];for(const file of files){const type=String(file.type||"image/jpeg").split(";")[0];if(!type.startsWith("image/"))continue;const ext=type.includes("png")?"png":type.includes("webp")?"webp":type.includes("gif")?"gif":"jpg";const key=id+"/manual-"+String(pos).padStart(3,"0")+"-"+crypto.randomUUID().slice(0,8)+"."+ext;await c.env.PHOTOS.put(key,await file.arrayBuffer(),{httpMetadata:{contentType:type,cacheControl:"public,max-age=31536000,immutable"}});const url="/media/"+key;await c.env.DB.prepare("INSERT INTO photos(id,car_id,url,position,processed) VALUES(?,?,?,?,0)").bind(crypto.randomUUID(),id,url,pos).run();urls.push(url);pos++}if(!urls.length)return json({error:"Nepodarilo sa uložiť žiadnu fotografiu."},400);return json({ok:true,count:urls.length,urls})}catch(e){return json({error:"Nahratie fotografií zlyhalo: "+String(e?.message||e)},500)}});
app.patch("/api/cars/:id",async c=>{if(!c.env.DB)return c.json({error:"DB nie je nakonfigurovaná."},503);const id=c.req.param("id"),b=await c.req.json(),allowed=["title","subtitle","year","km","power","range_km","drive","color","price_eur","purchase_price_eur","status","description"],sets=[],vals=[];for(const k of allowed)if(k in b){sets.push(k+"=?");vals.push(k.includes("price")?Number(b[k]):b[k])}if(!sets.length)return c.json({ok:true});sets.push("updated_at=CURRENT_TIMESTAMP");await c.env.DB.prepare("UPDATE cars SET "+sets.join(",")+" WHERE id=?").bind(...vals,id).run();return c.json({ok:true})});
app.delete("/api/cars/:id",async c=>{if(!c.env.DB)return c.json({error:"DB nie je nakonfigurovaná."},503);await c.env.DB.prepare("DELETE FROM cars WHERE id=?").bind(c.req.param("id")).run();return c.json({ok:true})});
app.all("*",async c=>c.env.ASSETS.fetch(c.req.raw));export default app;